sync_changes_to_github:
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_PATH == "awesome-scripts/awesome-userscripts"
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://gitlab.com/awesome-scripts/awesome-userscripts.git
    - git push --force -o ci.skip https://${GITHUB_SYNC_PAT}@github.com/awesome-scripts/awesome-userscripts.git HEAD:master
