name: Sync changes to GitLab

on:
  push:
    branches: [master]

jobs:
  build:
    if: (github.repository == 'awesome-scripts/awesome-userscripts')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout awesome-scripts/awesome-userscripts
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Push changes to gitlab.com/awesome-scripts/awesome-userscripts
        env:
          GITLAB_SYNC_PAT: ${{ secrets.GITLAB_SYNC_PAT }}
        run: |
          git push --force -o ci.skip \
            https://oauth2:$GITLAB_SYNC_PAT@gitlab.com/awesome-scripts/awesome-userscripts.git master
